version: '3.8'

services:
  nestjs-app:
    image: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    restart: always
    command: npm run start:prod
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
